feat(01): adding pnpm

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,24 +21,13 @@ jobs:
       LoadBalancerUrl: ${{ steps.get-outputs.outputs.LoadBalancerUrl }}
 
     steps:
-      - uses: actions/checkout@v4
-
-      - name: Validate Password
-        id: password-check
-        run: |
-          if [ "${{ github.event.inputs.password }}" != "${{ secrets.DEPLOY_PASSWORD }}" ]; then
-            echo "Invalid password"
-            exit 1
-          fi
-          echo "Password validated successfully"
+     - name: Checkout code
+        uses: actions/checkout@v3
 
       - name: Use Node.js 18.x
         uses: actions/setup-node@v3
         with:
           node-version: '18.x'
-
-      - name: Install pnpm
-        run: npm install -g pnpm
 
       - name: Cache pnpm modules
         uses: actions/cache@v3
@@ -49,8 +38,18 @@ jobs:
           key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
           restore-keys: |
             ${{ runner.os }}-pnpm-
-      - name: Install project dependencies
-        run: pnpm --prefer-offline
+
+      - name: Install dependencies
+        run: pnpm install
+
+      - name: Validate Password
+        id: password-check
+        run: |
+          if [ "${{ github.event.inputs.password }}" != "${{ secrets.DEPLOY_PASSWORD }}" ]; then
+            echo "Invalid password"
+            exit 1
+          fi
+          echo "Password validated successfully"
 
       - uses: actions/setup-java@v3
         with:
